parameters:
    tables.phpbbgallery.albums: %core.table_prefix%gallery_albums
    tables.phpbbgallery.albums_tracking: %core.table_prefix%gallery_albums_track
    tables.phpbbgallery.contests: %core.table_prefix%gallery_contests
    tables.phpbbgallery.moderators_cache: %core.table_prefix%gallery_modscache